/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolytopesRouteImport } from './routes/polytopes'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as HeuristicsRouteImport } from './routes/heuristics'
import { Route as CorrelationsRouteImport } from './routes/correlations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolytopeIdRouteImport } from './routes/polytope.$id'

const PolytopesRoute = PolytopesRouteImport.update({
  id: '/polytopes',
  path: '/polytopes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const HeuristicsRoute = HeuristicsRouteImport.update({
  id: '/heuristics',
  path: '/heuristics',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationsRoute = CorrelationsRouteImport.update({
  id: '/correlations',
  path: '/correlations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolytopeIdRoute = PolytopeIdRouteImport.update({
  id: '/polytope/$id',
  path: '/polytope/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/correlations': typeof CorrelationsRoute
  '/heuristics': typeof HeuristicsRoute
  '/playground': typeof PlaygroundRoute
  '/polytopes': typeof PolytopesRoute
  '/polytope/$id': typeof PolytopeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/correlations': typeof CorrelationsRoute
  '/heuristics': typeof HeuristicsRoute
  '/playground': typeof PlaygroundRoute
  '/polytopes': typeof PolytopesRoute
  '/polytope/$id': typeof PolytopeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/correlations': typeof CorrelationsRoute
  '/heuristics': typeof HeuristicsRoute
  '/playground': typeof PlaygroundRoute
  '/polytopes': typeof PolytopesRoute
  '/polytope/$id': typeof PolytopeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/correlations'
    | '/heuristics'
    | '/playground'
    | '/polytopes'
    | '/polytope/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/correlations'
    | '/heuristics'
    | '/playground'
    | '/polytopes'
    | '/polytope/$id'
  id:
    | '__root__'
    | '/'
    | '/correlations'
    | '/heuristics'
    | '/playground'
    | '/polytopes'
    | '/polytope/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorrelationsRoute: typeof CorrelationsRoute
  HeuristicsRoute: typeof HeuristicsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PolytopesRoute: typeof PolytopesRoute
  PolytopeIdRoute: typeof PolytopeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polytopes': {
      id: '/polytopes'
      path: '/polytopes'
      fullPath: '/polytopes'
      preLoaderRoute: typeof PolytopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heuristics': {
      id: '/heuristics'
      path: '/heuristics'
      fullPath: '/heuristics'
      preLoaderRoute: typeof HeuristicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlations': {
      id: '/correlations'
      path: '/correlations'
      fullPath: '/correlations'
      preLoaderRoute: typeof CorrelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polytope/$id': {
      id: '/polytope/$id'
      path: '/polytope/$id'
      fullPath: '/polytope/$id'
      preLoaderRoute: typeof PolytopeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorrelationsRoute: CorrelationsRoute,
  HeuristicsRoute: HeuristicsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PolytopesRoute: PolytopesRoute,
  PolytopeIdRoute: PolytopeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
