/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HeuristicsRouteImport } from './routes/heuristics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PolytopeIdRouteImport } from './routes/polytope.$id'
import { Route as GenomePolytopeIdRouteImport } from './routes/genome.$polytopeId'

const HeuristicsRoute = HeuristicsRouteImport.update({
  id: '/heuristics',
  path: '/heuristics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolytopeIdRoute = PolytopeIdRouteImport.update({
  id: '/polytope/$id',
  path: '/polytope/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenomePolytopeIdRoute = GenomePolytopeIdRouteImport.update({
  id: '/genome/$polytopeId',
  path: '/genome/$polytopeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/heuristics': typeof HeuristicsRoute
  '/genome/$polytopeId': typeof GenomePolytopeIdRoute
  '/polytope/$id': typeof PolytopeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heuristics': typeof HeuristicsRoute
  '/genome/$polytopeId': typeof GenomePolytopeIdRoute
  '/polytope/$id': typeof PolytopeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/heuristics': typeof HeuristicsRoute
  '/genome/$polytopeId': typeof GenomePolytopeIdRoute
  '/polytope/$id': typeof PolytopeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/heuristics' | '/genome/$polytopeId' | '/polytope/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/heuristics' | '/genome/$polytopeId' | '/polytope/$id'
  id: '__root__' | '/' | '/heuristics' | '/genome/$polytopeId' | '/polytope/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeuristicsRoute: typeof HeuristicsRoute
  GenomePolytopeIdRoute: typeof GenomePolytopeIdRoute
  PolytopeIdRoute: typeof PolytopeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/heuristics': {
      id: '/heuristics'
      path: '/heuristics'
      fullPath: '/heuristics'
      preLoaderRoute: typeof HeuristicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polytope/$id': {
      id: '/polytope/$id'
      path: '/polytope/$id'
      fullPath: '/polytope/$id'
      preLoaderRoute: typeof PolytopeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genome/$polytopeId': {
      id: '/genome/$polytopeId'
      path: '/genome/$polytopeId'
      fullPath: '/genome/$polytopeId'
      preLoaderRoute: typeof GenomePolytopeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeuristicsRoute: HeuristicsRoute,
  GenomePolytopeIdRoute: GenomePolytopeIdRoute,
  PolytopeIdRoute: PolytopeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
