/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenomePolytopeIdRouteImport } from './routes/genome.$polytopeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenomePolytopeIdRoute = GenomePolytopeIdRouteImport.update({
  id: '/genome/$polytopeId',
  path: '/genome/$polytopeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genome/$polytopeId': typeof GenomePolytopeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genome/$polytopeId': typeof GenomePolytopeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/genome/$polytopeId': typeof GenomePolytopeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/genome/$polytopeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/genome/$polytopeId'
  id: '__root__' | '/' | '/genome/$polytopeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenomePolytopeIdRoute: typeof GenomePolytopeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genome/$polytopeId': {
      id: '/genome/$polytopeId'
      path: '/genome/$polytopeId'
      fullPath: '/genome/$polytopeId'
      preLoaderRoute: typeof GenomePolytopeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenomePolytopeIdRoute: GenomePolytopeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
